version: "3.9"

services:
  mongo:
    image: mongo
    restart: always
    ports:
      - "27017:27017"

  # api:
  #   build: ./api
  #   restart: unless-stopped
  #   ports:
  #     - "8080:8080"
  #   depends_on:
  #     - mongo
  #   volumes:
  #     - ./api:/api
  #     - /api/node_modules